#pragma once
#include <iostream>
#include <algorithm>
#include <ctime>
#include <SFML/Main.hpp>
#include <SFML/Window.hpp>
#include <SFML/Graphics.hpp>
#include <sstream>
#include <SFML/System/Utf.hpp>
#include <queue>
#include <stack>